theme: jekyll-theme-cayman
show_downloads: false

collections:
  archives:
    label: archives
    path: archives
    output: true
    permalink: /archives/:path/

defaults:
  - scope:
    path: 'archives'
    type: archives

